timelogger/logs/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views


app_name = 'logs'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})$', views.logs_view, name="logs_view"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/create$', views.log_create, name="create"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/delete$', views.log_delete, name="delete"),
]

timelogger/timelogger/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^accounts/',include('allauth.urls')),
    #url(r'^accounts/', include('accounts.urls')),
    url(r'^logs/', include('logs.urls')),
    url(r'^admin/', admin.site.urls),
]

timelogger/logs/models.py
import datetime
from decimal import Decimal

from django.db import models
from django.utils import timezone
from django.db.models import Sum
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator


class Project(models.Model):

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)

    def __str__(self):
        return self.title

    def get_total_hours(self):
        logs = Log.objects.filter(project=self)
        total = logs.aggregate(Sum('duration'))
        return total['duration__sum']


class Log(models.Model):

    project = models.ForeignKey(
        Project, 
        on_delete=models.SET_NULL, 
        blank=True, null=True
    )
    day = models.DateField('day')
    duration = models.DecimalField(max_digits=4, decimal_places=2, validators=[MinValueValidator(Decimal(0.01))])
    logtime = models.DateTimeField('logtime')
    user = models.ForeignKey(User, default=None, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.day)
    
    def is_late(self):
        return self.logtime.date() > self.day

timelogger/logs/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

from . import models

class DateInput(forms.DateInput):
    input_type = 'date'


class CreateLog(forms.ModelForm):

    duration = forms.DecimalField(widget=forms.NumberInput(attrs={'min':0.01, 'max':99}), max_digits=4, decimal_places=2, validators=[MinValueValidator(0.01)])

    class Meta:
        model = models.Log
        fields = ['project', 'duration']
        widgets = {
            'day': DateInput(),
        }

timelogger/logs/views.py
import datetime

from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import generic
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Sum

from . import forms
from .models import Project, Log


@login_required(login_url="/accounts/login/")
def index(request):
    if request.method == 'GET':
        now = datetime.datetime.now()
        return redirect(reverse('logs:logs_view', args=(now.year, now.month, now.day,)))
    else:
        #change day
        new_day = datetime.datetime.strptime(request.POST.get('day'), '%Y-%m-%d').date()
        return redirect(reverse('logs:logs_view', args=(new_day.year, new_day.month, new_day.day,)))



@login_required(login_url="/accounts/login/")
def logs_view(request, year, month, day):

    form = forms.CreateLog()

    selected_day = datetime.date(int(year), int(month), int(day))

    logs = Log.objects.filter(
        day__year = selected_day.year,
        day__month = selected_day.month,
        day__day = selected_day.day,
        user = request.user,
    ).order_by('-logtime')

    day_sum = logs.aggregate(Sum('duration'))


    month_logs = Log.objects.filter(
        day__year = selected_day.year,
        day__month = selected_day.month,
        user = request.user,
    )

    month_sum = month_logs.aggregate(Sum('duration'))


    week_logs = Log.objects.filter(
        day__week = selected_day.isocalendar()[1],
    )

    week_sum = week_logs.aggregate(Sum('duration'))

    context = {
        'createlogform': form,
        'date': selected_day,
        'logs': logs,
        'day_sum': day_sum,
        'month_sum': month_sum,
        'week_sum': week_sum,
    }



    return render(request, 'logs/index.html', context)


@login_required(login_url="/accounts/login/")
def log_create(request, year, month, day):
    if request.method == 'POST':
        form = forms.CreateLog(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.logtime = timezone.now()
            instance.day = datetime.date(int(year), int(month), int(day))
            instance.save()
            return redirect(reverse('logs:logs_view', args=(year, month, day,)))


@login_required(login_url="/accounts/login/")
def log_delete(request, year, month, day):
    if request.method == 'POST':
        log_id = request.POST['id']
        log = Log.objects.filter(id=log_id)
        log.delete()
        return redirect(reverse('logs:logs_view', args=(year, month, day,)))

timelogger/timelogger/views.py
from django.shortcuts import render, redirect
from django.urls import reverse


def index(request):
    return redirect(reverse('logs:index'))

timelogger/logs/templates/logs/index.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p>Selected day:</p>
                <h2>{{ date }}</h2>
                
            </div>
            <div class="col-md-6 float-right">
                <form action="{% url 'logs:index' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Select day:</label>
                        <input type="date" class="form-control" name="day" id="day">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Change day">
                </form> 
                <br>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <h2>Log time:</h2>
                <form action="{% url 'logs:create' year=date.year month=date.month day=date.day %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ createlogform | crispy }}
                        <input type="submit" class="btn btn-primary" value="Create">
                    </div>
                </form>
            </div>
        </div>
            
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-center">{{ user.username }}'s log history for {{ date }}.</h3>
                <br>
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Project</th> 
                        <th>Time</th>
                        <th>Duration</th> 
                        <th>Action</th>
                    </tr>
                    {% for log in logs %}
                        <tr class="{% if log.is_late %}late-log{% endif %}">
                            <td>{{log.project}}</td>
                            <td>{{log.logtime}}</td>
                            <td>{{log.duration}} hours</td>
                            <td>
                                <div class="text-center">
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#modal{{log.id}}">
                                        Delete entry
                                    </button>
                                </div>
                                
                                
                                <!-- Modal -->
                                <div class="modal fade" id="modal{{log.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete this entry?
                                        </div>
                                        <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <form action="{% url 'logs:delete' year=date.year month=date.month day=date.day %}" method="post">
                                            {% csrf_token %}
                                            <input id="id" name="id" type="hidden" value="{{log.id}}">
                                            <input type="submit" class="btn btn-danger" value="Confirm">
                                        </form>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        
        <blockquote class="text-center">
            <p>Total time logged for the day: {{ day_sum.duration__sum | default_if_none:"0" }} hours.</p>
        </blockquote>
        <blockquote class="text-center">
            <p>Total time logged for the week: {{ week_sum.duration__sum | default_if_none:"0" }} hours.</p>
        </blockquote>
        <blockquote class="text-center">
            <p>Total time logged for the month: {{ month_sum.duration__sum | default_if_none:"0" }} hours.</p>
        </blockquote>

    </div>
    
{% endblock %}

timelogger/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
	{% if user.is_authenticated %}
	<li><a href="{% url 'account_email' %}">Change E-mail</a></li>
	<li><a href="{% url 'account_logout' %}">Sign Out</a></li>
	{% else %}
	<li><a href="{% url 'account_login' %}">Sign In</a></li>
	<li><a href="{% url 'account_signup' %}">Sign Up</a></li>
	{% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

timelogger/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <title>Timelogger</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Welcome {{user.username}}!</a>
            {% if user.is_authenticated %}
                <form class="logout-link" action="{% url 'account_logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-success">Logout</button>
                </form>
            {% endif %}
        </div>
        
    </nav>
    <br>
    <div>
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'jquery.js' %}"></script>
    <script src="{% static 'jquery-ui.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

</body>
</html>

timelogger/templates/index.html
{% load socialaccount %}
{% providers_media_js %}
<h1>Index</h1>
<a href="{% provider_login_url "facebook" method="js_sdk" %}">Login with Facebook</a>
<a href="{% provider_login_url "google" method="js_sdk" %}">Login with Google</a>